#!/usr/bin/env python3
"""atlas_validate — makes Atlas's derived views genuinely derived.

Usage:  python atlas_validate.py [project-vault-root]   (default: cwd)

Reads   registry/io-graph.yml            (source of truth: components + edges + pins)
        components/*/docs/provides/*.md  (contract frontmatter: interface, version, status)
Emits   registry/graph.md                (Mermaid diagram + edge table)
        registry/.compiled/<slug>/io-manifest.yml
        dashboard.md                     (drift panel, between atlas:drift markers)
        components/<slug>/component.md   (edge block, between atlas:edges markers)
Prints  a drift report. Exit 1 on breaking (major) drift, else 0.

Edge facts are edited ONLY in io-graph.yml. See meta/AAC-method.md §8.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

ROOT = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path.cwd()
GENERATED_NOTE = "generated by tools/atlas_validate.py — edit registry/io-graph.yml instead"


def parse_frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.DOTALL)
    if not m:
        return {}
    try:
        return yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError:
        return {}


def version_tuple(v) -> tuple:
    parts = str(v).split(".")
    return tuple(int(p) if p.isdigit() else 0 for p in parts)


def load_graph() -> dict:
    return yaml.safe_load((ROOT / "registry" / "io-graph.yml").read_text(encoding="utf-8"))


def latest_contract_versions() -> dict:
    """interface -> (version, status, path) from every live docs/provides/*.md."""
    latest = {}
    for path in ROOT.glob("components/*/docs/provides/*.md"):
        fm = parse_frontmatter(path)
        iface = fm.get("interface") or fm.get("contract")
        if not iface or fm.get("status") in ("superseded",):
            continue
        ver = fm.get("version")
        if ver is None:
            continue
        if iface not in latest or version_tuple(ver) > version_tuple(latest[iface][0]):
            latest[iface] = (str(ver), fm.get("status", "?"), path.relative_to(ROOT))
    return latest


def drift_state(pinned: str, latest: str | None) -> tuple[str, str]:
    """-> (emoji, label)."""
    if latest is None:
        return "⚪", "no contract file yet"
    p, l = version_tuple(pinned), version_tuple(latest)
    if l <= p:
        return "🟢", "aligned"
    if l[0] > p[0]:
        return "🔴", f"BREAKING — latest {latest}, review required"
    return "🟠", f"latest {latest} — re-pin when convenient"


def replace_block(path: Path, marker: str, body: str) -> bool:
    text = path.read_text(encoding="utf-8")
    pattern = re.compile(
        rf"(<!-- atlas:{marker}:begin[^>]*-->).*?(<!-- atlas:{marker}:end -->)", re.DOTALL
    )
    if not pattern.search(text):
        print(f"  WARN: no atlas:{marker} markers in {path.relative_to(ROOT)}")
        return False
    path.write_text(pattern.sub(rf"\1\n{body}\n\2", text), encoding="utf-8")
    return True


def edge_rows(graph, latest):
    rows = []
    for e in graph.get("edges", []):
        lv = latest.get(e["interface"], (None,))[0]
        emoji, label = drift_state(str(e["pinned"]), lv)
        rows.append({**e, "latest": lv or "—", "emoji": emoji, "label": label})
    return rows


def gen_graph_md(graph, rows) -> str:
    names = {c["slug"]: c for c in graph["components"]}
    ids = {slug: re.sub(r"[^a-z0-9]", "", slug) for slug in names}
    lines = [
        "---", "title: I/O Graph — rendered view", "type: graph-view", "---", "",
        "# I/O Graph (rendered)", "",
        f"> **Generated file** — {GENERATED_NOTE}.",
        "> Arrows point **provider → consumer** (upstream → downstream).", "",
        "```mermaid", "flowchart LR",
        "    classDef sink fill:#2d3a2e,stroke:#7fbf7f,color:#eee;",
    ]
    for slug, c in names.items():
        m = c.get("maturity", "?")
        cls = ":::sink" if slug == "ansible-platform" else ""
        lines.append(f'    {ids[slug]}["{c["name"]}<br/><small>{m}</small>"]{cls}')
    for r in rows:
        arrow = "==>" if r.get("mode") == "collaboration" else "-->"
        mark = "" if r["emoji"] == "🟢" else f" {r['emoji']}"
        lines.append(f'    {ids[r["from"]]} {arrow}|"{r["interface"]}{mark}"| {ids[r["to"]]}')
    lines += [
        "```", "",
        "**Legend:** solid = x-as-a-service · thick `==` = collaboration · "
        "🟠 minor drift · 🔴 breaking drift · ⚪ contract not yet published in Atlas.", "",
        "## Edges", "",
        "| Provider → Consumer | Interface | Mode | Pinned | Latest | State |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {names[r['from']]['name']} → {names[r['to']]['name']} | {r['interface']} "
            f"| {r.get('mode', '?')} | {r['pinned']} | {r['latest']} | {r['emoji']} {r['label']} |"
        )
    return "\n".join(lines) + "\n"


def gen_component_block(slug, graph, rows, names) -> str:
    up = [r for r in rows if r["to"] == slug]
    down = [r for r in rows if r["from"] == slug]
    def fmt(r, other):
        link = f"[[{other}/component|{names[other]['name']}]]"
        return f"{link} — `{r['interface']}` (pinned {r['pinned']}) {r['emoji']}"
    lines = []
    lines.append("- **Upstream (I depend on):** " + ("; ".join(fmt(r, r["from"]) for r in up) or "_none_"))
    lines.append("- **Downstream (depend on me):** " + ("; ".join(fmt(r, r["to"]) for r in down) or "_none — terminal sink_"))
    lines.append("- **I provide** (`docs/provides/`): " + (", ".join(f"`{r['interface']}`" for r in down) or "_no registered interfaces_"))
    lines.append("- **I read:** providers' `docs/provides/` above; my consumers' `docs/needs/` for feedback.")
    return "\n".join(lines)


def gen_manifest(slug, rows) -> dict:
    return {
        "component": slug,
        "generated_by": "Atlas/tools/atlas_validate.py",
        "read_before_working": {
            "constitution": "architecture/constitution.md",
            "inputs": [
                {
                    "provider": r["from"],
                    "interface": r["interface"],
                    "pinned": r["pinned"],
                    "path": f"components/{r['from']}/docs/provides/",
                    "state": r["label"],
                }
                for r in rows if r["to"] == slug
            ],
            "consumer_feedback": [
                {"consumer": r["to"], "path": f"components/{r['to']}/docs/needs/"}
                for r in rows if r["from"] == slug
            ],
            "proposals": "architecture/proposals/",
        },
    }


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    if not (ROOT / "registry" / "io-graph.yml").exists():
        print(f"No registry/io-graph.yml under {ROOT} — run from a project-vault root "
              "or pass the vault path as the first argument.")
        return 2
    graph = load_graph()
    names = {c["slug"]: c for c in graph["components"]}

    # -- referential integrity ------------------------------------------------
    errors = []
    for e in graph.get("edges", []):
        for end in ("from", "to"):
            if e[end] not in names:
                errors.append(f"edge {e['from']}->{e['to']}: unknown component '{e[end]}'")
    for c in graph["components"]:
        if not (ROOT / "components" / c["slug"] / "component.md").exists():
            errors.append(f"component '{c['slug']}' has no components/{c['slug']}/component.md")
    if errors:
        print("INTEGRITY ERRORS:")
        for err in errors:
            print(f"  ✗ {err}")
        return 1

    latest = latest_contract_versions()
    rows = edge_rows(graph, latest)

    # -- regenerate derived views ---------------------------------------------
    (ROOT / "registry" / "graph.md").write_text(gen_graph_md(graph, rows), encoding="utf-8")
    print("regenerated registry/graph.md")

    drift_table = "\n".join(
        ["| Edge (provider → consumer) | Interface | Pinned | Latest | State |", "|---|---|---|---|---|"]
        + [
            f"| {r['from']} → {r['to']} | {r['interface']} | {r['pinned']} | {r['latest']} | {r['emoji']} {r['label']} |"
            for r in sorted(rows, key=lambda r: ("🔴🟠⚪🟢".index(r["emoji"]),))
        ]
    )
    replace_block(ROOT / "dashboard.md", "drift", drift_table)
    print("regenerated dashboard.md drift panel")

    for slug in names:
        replace_block(
            ROOT / "components" / slug / "component.md", "edges",
            gen_component_block(slug, graph, rows, names),
        )
        out = ROOT / "registry" / ".compiled" / slug
        out.mkdir(parents=True, exist_ok=True)
        (out / "io-manifest.yml").write_text(
            yaml.safe_dump(gen_manifest(slug, rows), sort_keys=False, allow_unicode=True),
            encoding="utf-8",
        )
    print(f"regenerated {len(names)} component edge blocks + io-manifests")

    # -- drift report -----------------------------------------------------------
    print("\nDRIFT REPORT")
    worst = 0
    for r in rows:
        print(f"  {r['emoji']} {r['from']} → {r['to']}  {r['interface']}  pinned {r['pinned']}  ({r['label']})")
        if r["emoji"] == "🔴":
            worst = 1
    print(f"\n{sum(r['emoji'] == '🟢' for r in rows)} aligned, "
          f"{sum(r['emoji'] == '🟠' for r in rows)} minor drift, "
          f"{sum(r['emoji'] == '🔴' for r in rows)} breaking, "
          f"{sum(r['emoji'] == '⚪' for r in rows)} unpublished")
    return worst


if __name__ == "__main__":
    sys.exit(main())
