#!/usr/bin/env python3
"""atlas_validate — makes Atlas's derived views genuinely derived.

Usage:  python atlas_validate.py [project-vault-root]                  (default: cwd)
        python atlas_validate.py [project-vault-root] --emit-context <slug> [--out <path>]

Validate mode
Reads   registry/io-graph.yml            (source of truth: components + edges + pins)
        components/*/docs/provides/*.md  (contract frontmatter: interface, version, status)
Emits   registry/graph.md                (Mermaid diagram + edge table)
        registry/.compiled/<slug>/io-manifest.yml
        dashboard.md                     (drift panel, between atlas:drift markers)
        components/<slug>/component.md   (edge block, between atlas:edges markers)
Prints  a drift report. Exit 1 on breaking (major) drift, else 0.

Context mode (--emit-context <slug>)
Reads   registry/.compiled/<slug>/io-manifest.yml   (run validate mode first)
Emits   one ATLAS-CONTEXT.md to stdout (or --out <path>): the component's complete
        session reading list — constitution, pinned upstream contracts, consumers'
        needs addressed to it, in-flight proposals touching it, and a drift summary.
        A byte/token estimate is printed to stderr.
This is the retrieval boundary of the method: a session reads ATLAS-CONTEXT.md, not
the vault. If the context proves insufficient, the io-graph is wrong — fix the graph.

Edge facts are edited ONLY in io-graph.yml. See AAC-method.md §8.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

ROOT = Path.cwd()  # reassigned from CLI args in __main__
GENERATED_NOTE = "generated by tools/atlas_validate.py — edit registry/io-graph.yml instead"


def parse_frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.DOTALL)
    if not m:
        return {}
    try:
        return yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError:
        return {}


def version_tuple(v) -> tuple:
    parts = str(v).split(".")
    return tuple(int(p) if p.isdigit() else 0 for p in parts)


def load_graph() -> dict:
    return yaml.safe_load((ROOT / "registry" / "io-graph.yml").read_text(encoding="utf-8"))


def latest_contract_versions() -> dict:
    """interface -> (version, status, path) from every live docs/provides/*.md."""
    latest = {}
    for path in ROOT.glob("components/*/docs/provides/*.md"):
        fm = parse_frontmatter(path)
        iface = fm.get("interface") or fm.get("contract")
        if not iface or fm.get("status") in ("superseded",):
            continue
        ver = fm.get("version")
        if ver is None:
            continue
        if iface not in latest or version_tuple(ver) > version_tuple(latest[iface][0]):
            latest[iface] = (str(ver), fm.get("status", "?"), path.relative_to(ROOT))
    return latest


def drift_state(pinned: str, latest: str | None) -> tuple[str, str]:
    """-> (emoji, label)."""
    if latest is None:
        return "⚪", "no contract file yet"
    p, l = version_tuple(pinned), version_tuple(latest)
    if l <= p:
        return "🟢", "aligned"
    if l[0] > p[0]:
        return "🔴", f"BREAKING — latest {latest}, review required"
    return "🟠", f"latest {latest} — re-pin when convenient"


def replace_block(path: Path, marker: str, body: str) -> bool:
    text = path.read_text(encoding="utf-8")
    pattern = re.compile(
        rf"(<!-- atlas:{marker}:begin[^>]*-->).*?(<!-- atlas:{marker}:end -->)", re.DOTALL
    )
    if not pattern.search(text):
        print(f"  WARN: no atlas:{marker} markers in {path.relative_to(ROOT)}")
        return False
    path.write_text(pattern.sub(rf"\1\n{body}\n\2", text), encoding="utf-8")
    return True


def edge_rows(graph, latest):
    rows = []
    for e in graph.get("edges", []):
        lv = latest.get(e["interface"], (None,))[0]
        emoji, label = drift_state(str(e["pinned"]), lv)
        rows.append({**e, "latest": lv or "—", "emoji": emoji, "label": label})
    return rows


def gen_graph_md(graph, rows) -> str:
    names = {c["slug"]: c for c in graph["components"]}
    ids = {slug: re.sub(r"[^a-z0-9]", "", slug) for slug in names}
    lines = [
        "---", "title: I/O Graph — rendered view", "type: graph-view", "---", "",
        "# I/O Graph (rendered)", "",
        f"> **Generated file** — {GENERATED_NOTE}.",
        "> Arrows point **provider → consumer** (upstream → downstream).", "",
        "```mermaid", "flowchart LR",
        "    classDef sink fill:#2d3a2e,stroke:#7fbf7f,color:#eee;",
    ]
    for slug, c in names.items():
        m = c.get("maturity", "?")
        cls = ":::sink" if c.get("sink") else ""  # `sink: true` on the io-graph entry
        lines.append(f'    {ids[slug]}["{c["name"]}<br/><small>{m}</small>"]{cls}')
    for r in rows:
        arrow = "==>" if r.get("mode") == "collaboration" else "-->"
        mark = "" if r["emoji"] == "🟢" else f" {r['emoji']}"
        lines.append(f'    {ids[r["from"]]} {arrow}|"{r["interface"]}{mark}"| {ids[r["to"]]}')
    lines += [
        "```", "",
        "**Legend:** solid = x-as-a-service · thick `==` = collaboration · "
        "🟠 minor drift · 🔴 breaking drift · ⚪ contract not yet published in Atlas.", "",
        "## Edges", "",
        "| Provider → Consumer | Interface | Mode | Pinned | Latest | State |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {names[r['from']]['name']} → {names[r['to']]['name']} | {r['interface']} "
            f"| {r.get('mode', '?')} | {r['pinned']} | {r['latest']} | {r['emoji']} {r['label']} |"
        )
    return "\n".join(lines) + "\n"


def gen_component_block(slug, graph, rows, names) -> str:
    up = [r for r in rows if r["to"] == slug]
    down = [r for r in rows if r["from"] == slug]
    def fmt(r, other):
        link = f"[[{other}/component|{names[other]['name']}]]"
        return f"{link} — `{r['interface']}` (pinned {r['pinned']}) {r['emoji']}"
    lines = []
    lines.append("- **Upstream (I depend on):** " + ("; ".join(fmt(r, r["from"]) for r in up) or "_none_"))
    lines.append("- **Downstream (depend on me):** " + ("; ".join(fmt(r, r["to"]) for r in down) or "_none — terminal sink_"))
    lines.append("- **I provide** (`docs/provides/`): " + (", ".join(f"`{r['interface']}`" for r in down) or "_no registered interfaces_"))
    lines.append("- **I read:** providers' `docs/provides/` above; my consumers' `docs/needs/` for feedback.")
    return "\n".join(lines)


def gen_manifest(slug, rows) -> dict:
    return {
        "component": slug,
        "generated_by": "Atlas/tools/atlas_validate.py",
        "read_before_working": {
            "constitution": "architecture/constitution.md",
            "inputs": [
                {
                    "provider": r["from"],
                    "interface": r["interface"],
                    "pinned": r["pinned"],
                    "path": f"components/{r['from']}/docs/provides/",
                    "state": r["label"],
                }
                for r in rows if r["to"] == slug
            ],
            "consumer_feedback": [
                {"consumer": r["to"], "path": f"components/{r['to']}/docs/needs/"}
                for r in rows if r["from"] == slug
            ],
            "proposals": "architecture/proposals/",
        },
    }


# --------------------------------------------------------------------------- #
# Context mode — the retrieval boundary (AAC-method §6).                       #
# Everything below only READS the vault and concatenates; it never mutates.    #
# --------------------------------------------------------------------------- #

def read_doc(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8").strip()
    except OSError as exc:
        return f"_[unreadable: {exc}]_"


def contract_at_pin(provides_dir: Path, interface: str, pinned: str):
    """-> (path, version, note) — the contract file for `interface` at `pinned`.

    Resolution rule (explicit): on an exact MAJOR.MINOR match, the live folder wins
    over archive/. If the pin is gone entirely, fall back to the newest **live**
    version with a note (drift the session must see); archive/ is consulted for the
    fallback only when the live folder has no candidate at all.
    """
    def scan(folder: Path):
        out = []
        for p in sorted(folder.glob("*.md")):
            fm = parse_frontmatter(p)
            if (fm.get("interface") or fm.get("contract")) != interface:
                continue
            ver = fm.get("version")
            if ver is not None:
                out.append((p, str(ver)))
        return out

    live, archived = scan(provides_dir), scan(provides_dir / "archive")
    if not live and not archived:
        return None, None, f"no contract file for `{interface}` under {provides_dir}"
    want = version_tuple(pinned)[:2]
    for p, ver in live + archived:  # live listed first — live wins on exact match
        if version_tuple(ver)[:2] == want:
            return p, ver, ""
    p, ver = max(live or archived, key=lambda c: version_tuple(c[1]))
    return p, ver, f"pinned {pinned} not found — showing latest {ver}; re-pin deliberately"


def addressed_to(fm: dict, slug: str) -> bool:
    """A needs/ doc is in scope if its `to:` names the slug, or has no `to:` at all."""
    to = fm.get("to")
    if to is None:
        return True
    if isinstance(to, list):
        to = "; ".join(str(t) for t in to)
    return slug.lower() in str(to).lower()


def proposal_in_flight(fm: dict, slug: str) -> bool:
    status = str(fm.get("status", "proposed")).lower()
    if any(s in status for s in ("accepted", "rejected", "implemented", "superseded",
                                 "withdrawn", "done", "closed")):
        return False
    scope = " ".join(str(fm.get(k, "")) for k in ("affects", "target_component", "related"))
    return slug.lower() in scope.lower()


def emit_context(slug: str, out: str | None) -> int:
    manifest_path = ROOT / "registry" / ".compiled" / slug / "io-manifest.yml"
    if not manifest_path.exists():
        print(f"No {manifest_path.relative_to(ROOT).as_posix()} in the vault — the compiled "
              "manifests must be committed (AAC-method §5); regenerate with the validator "
              "(no flags) on the vault's default branch.", file=sys.stderr)
        return 2
    manifest = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
    reading = manifest.get("read_before_working", {})
    sections: list[str] = [
        f"# ATLAS-CONTEXT — {slug}",
        "",
        f"> Generated by tools/atlas_validate.py --emit-context from "
        f"`{manifest_path.relative_to(ROOT).as_posix()}`. Do not edit.",
        "> This is the session's complete reading list. Consult the wider vault only if",
        "> this file is insufficient — and treat that as a defect in `registry/io-graph.yml`:",
        "> fix the graph, don't browse.",
    ]

    # 1. constitution
    const_rel = reading.get("constitution", "architecture/constitution.md")
    sections += [f"\n---\n\n## Constitution — `{const_rel}`\n", read_doc(ROOT / const_rel)]

    # 2. pinned upstream contracts
    inputs = reading.get("inputs", [])
    sections.append("\n---\n\n# Inputs — upstream contracts I build against\n")
    if not inputs:
        sections.append("_none — no upstream edges._")
    for inp in inputs:
        path, ver, note = contract_at_pin(
            ROOT / inp["path"], inp["interface"], str(inp["pinned"]))
        head = (f"## `{inp['interface']}` from {inp['provider']} — "
                f"pinned {inp['pinned']}, state: {inp.get('state', '?')}")
        if note:
            head += f"\n\n> ⚠ {note}"
        if path is None:
            sections += [head, "_contract not yet published._"]
        else:
            sections += [f"{head}\n\n**Source:** `{path.relative_to(ROOT).as_posix()}` "
                         f"(version {ver})\n", read_doc(path)]

    # 3. consumers' needs addressed to me
    sections.append("\n---\n\n# Consumer feedback — needs addressed to me\n")
    seen_dirs, any_needs = set(), False
    for fb in reading.get("consumer_feedback", []):
        needs_dir = ROOT / fb["path"]
        if needs_dir in seen_dirs:
            continue
        seen_dirs.add(needs_dir)
        for p in sorted(needs_dir.glob("*.md")):
            fm = parse_frontmatter(p)
            if str(fm.get("status", "")).lower().startswith("superseded"):
                continue
            if not addressed_to(fm, slug):
                continue
            any_needs = True
            sections += [f"## From {fb['consumer']} — `{p.relative_to(ROOT).as_posix()}` "
                         f"(version {fm.get('version', '?')})\n", read_doc(p)]
    if not any_needs:
        sections.append("_none pending._")

    # 4. in-flight proposals touching me
    proposals_dir = ROOT / reading.get("proposals", "architecture/proposals/")
    sections.append("\n---\n\n# In-flight proposals affecting me\n")
    hits = [p for p in sorted(proposals_dir.glob("*.md"))
            if proposal_in_flight(parse_frontmatter(p), slug)]
    if not hits:
        sections.append("_none in flight._")
    for p in hits:
        fm = parse_frontmatter(p)
        sections += [f"## `{p.relative_to(ROOT).as_posix()}` (status: {fm.get('status', '?')})\n",
                     read_doc(p)]

    # 5. drift summary
    sections.append("\n---\n\n# Drift summary (pinned vs latest, per edge)\n")
    if inputs:
        sections.append("| Provider | Interface | Pinned | State |\n|---|---|---|---|")
        sections += [f"| {i['provider']} | `{i['interface']}` | {i['pinned']} "
                     f"| {i.get('state', '?')} |" for i in inputs]
    else:
        sections.append("_no upstream edges._")

    text = "\n".join(sections) + "\n"
    if out:
        Path(out).write_text(text, encoding="utf-8")
        print(f"wrote {out}", file=sys.stderr)
    else:
        sys.stdout.write(text)
    size = len(text.encode("utf-8"))
    print(f"ATLAS-CONTEXT for {slug}: {size:,} bytes, ~{size // 4:,} tokens", file=sys.stderr)
    return 0


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    if not (ROOT / "registry" / "io-graph.yml").exists():
        print(f"No registry/io-graph.yml under {ROOT} — run from a project-vault root "
              "or pass the vault path as the first argument.")
        return 2
    graph = load_graph()
    names = {c["slug"]: c for c in graph["components"]}

    # -- referential integrity ------------------------------------------------
    errors = []
    for e in graph.get("edges", []):
        for end in ("from", "to"):
            if e[end] not in names:
                errors.append(f"edge {e['from']}->{e['to']}: unknown component '{e[end]}'")
    for c in graph["components"]:
        if not (ROOT / "components" / c["slug"] / "component.md").exists():
            errors.append(f"component '{c['slug']}' has no components/{c['slug']}/component.md")
    if errors:
        print("INTEGRITY ERRORS:")
        for err in errors:
            print(f"  ✗ {err}")
        return 1

    latest = latest_contract_versions()
    rows = edge_rows(graph, latest)

    # -- regenerate derived views ---------------------------------------------
    (ROOT / "registry" / "graph.md").write_text(gen_graph_md(graph, rows), encoding="utf-8")
    print("regenerated registry/graph.md")

    drift_table = "\n".join(
        ["| Edge (provider → consumer) | Interface | Pinned | Latest | State |", "|---|---|---|---|---|"]
        + [
            f"| {r['from']} → {r['to']} | {r['interface']} | {r['pinned']} | {r['latest']} | {r['emoji']} {r['label']} |"
            for r in sorted(rows, key=lambda r: ("🔴🟠⚪🟢".index(r["emoji"]),))
        ]
    )
    replace_block(ROOT / "dashboard.md", "drift", drift_table)
    print("regenerated dashboard.md drift panel")

    for slug in names:
        replace_block(
            ROOT / "components" / slug / "component.md", "edges",
            gen_component_block(slug, graph, rows, names),
        )
        out = ROOT / "registry" / ".compiled" / slug
        out.mkdir(parents=True, exist_ok=True)
        (out / "io-manifest.yml").write_text(
            yaml.safe_dump(gen_manifest(slug, rows), sort_keys=False, allow_unicode=True),
            encoding="utf-8",
        )
    print(f"regenerated {len(names)} component edge blocks + io-manifests")

    # -- drift report -----------------------------------------------------------
    print("\nDRIFT REPORT")
    worst = 0
    for r in rows:
        print(f"  {r['emoji']} {r['from']} → {r['to']}  {r['interface']}  pinned {r['pinned']}  ({r['label']})")
        if r["emoji"] == "🔴":
            worst = 1
    print(f"\n{sum(r['emoji'] == '🟢' for r in rows)} aligned, "
          f"{sum(r['emoji'] == '🟠' for r in rows)} minor drift, "
          f"{sum(r['emoji'] == '🔴' for r in rows)} breaking, "
          f"{sum(r['emoji'] == '⚪' for r in rows)} unpublished")
    return worst


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("root", nargs="?", default=".",
                    help="project-vault root (default: cwd)")
    ap.add_argument("--emit-context", metavar="SLUG",
                    help="emit the component's ATLAS-CONTEXT.md instead of validating")
    ap.add_argument("--out", metavar="PATH",
                    help="with --emit-context: write to PATH instead of stdout")
    args = ap.parse_args()
    ROOT = Path(args.root).resolve()
    if hasattr(sys.stderr, "reconfigure"):
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    if args.emit_context:
        if hasattr(sys.stdout, "reconfigure"):
            sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.exit(emit_context(args.emit_context, args.out))
    sys.exit(main())
