#!/usr/bin/env python3
"""atlas_validate — makes Atlas's derived views genuinely derived.

Usage:  python atlas_validate.py [project-vault-root]                  (default: cwd)
        python atlas_validate.py [project-vault-root] --emit-context <slug> [--out <path>]

Validate mode
Reads   registry/io-graph.yml            (source of truth: components + edges + pins)
        components/*/docs/provides/*.md  (contract frontmatter: interface, version, status)
Emits   registry/graph.md                (Mermaid diagram + edge table)
        registry/.compiled/<slug>/io-manifest.yml
        dashboard.md                     (drift panel, between atlas:drift markers)
        components/<slug>/component.md   (edge block, between atlas:edges markers)
Prints  a drift report, plus warn-only naming-canon notes for live-folder documents
        (AAC-method §4; archive/ and _triage/ are skipped). Exit 1 on breaking
        (major) drift, else 0 — naming never affects the exit code.
With    --check-wiring (opt-in; decisions/0001): also verifies each component repo is
        wired — default branch has .atlas.conf with the matching SLUG and a committed
        AGENTS.md, fetched from its source: URL. Warn-only; adds the Wired column to
        the dashboard estate table. CI runs this; plain local runs stay offline apart
        from the cheap ref-level branch checks.

Context mode (--emit-context <slug>)
Reads   registry/.compiled/<slug>/io-manifest.yml   (run validate mode first)
Emits   one ATLAS-CONTEXT.md to stdout (or --out <path>): the component's complete
        session reading list — constitution, pinned upstream contracts, consumers'
        needs addressed to it, in-flight proposals touching it, and a drift summary.
        A byte/token estimate is printed to stderr.
This is the retrieval boundary of the method: a session reads ATLAS-CONTEXT.md, not
the vault. If the context proves insufficient, the io-graph is wrong — fix the graph.

Edge facts are edited ONLY in io-graph.yml. See AAC-method.md §8.
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

ROOT = Path.cwd()  # reassigned from CLI args in __main__
METHOD_ROOT = Path(__file__).resolve().parent.parent
GENERATED_NOTE = "generated by tools/atlas_validate.py — edit registry/io-graph.yml instead"
DELIVERED_EXTERNAL: list = []   # set in main(); vault-level, same for every component


# A delivered copy (a provider's contract vendored into a consumer's vault) carries a
# blockquote banner naming its authored home. Tolerate that — and blank lines — ahead of
# the frontmatter, or every delivered contract parses as having none at all.
FRONTMATTER_RE = re.compile(r"^(?:\s*(?:>[^\n]*)?\n)*?---\s*\n(.*?)\n---\s*\n", re.DOTALL)


# Documents whose frontmatter will not parse. Collected, not raised (PR #7, AgentEco):
# one bad file must not stop the run, but an unparseable block is NOT an empty one —
# swallowing it makes a published contract read as never-published (🟢 -> ⚪) and a
# needs doc route to nobody, while looking correct to any human who opens it.
FRONTMATTER_ERRORS: list = []


def parse_frontmatter_text(text: str, source: str | None = None) -> dict:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    try:
        return yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError as exc:
        if source is not None:   # remote blobs (wiring/external probes) are the
            FRONTMATTER_ERRORS.append((source, str(exc).splitlines()[0].strip()))
        return {}                # provider's own vault's problem, not this one's


def parse_frontmatter(path: Path) -> dict:
    src = (path.relative_to(ROOT).as_posix()
           if path.is_absolute() and str(path).startswith(str(ROOT)) else path.as_posix())
    return parse_frontmatter_text(path.read_text(encoding="utf-8"), source=src)


def version_tuple(v) -> tuple:
    parts = str(v).split(".")
    return tuple(int(p) if p.isdigit() else 0 for p in parts)


def load_graph() -> dict:
    return yaml.safe_load((ROOT / "registry" / "io-graph.yml").read_text(encoding="utf-8"))


def latest_contract_versions() -> dict:
    """interface -> (version, status, path) from every live docs/provides/*.md."""
    latest = {}
    for path in ROOT.glob("components/*/docs/provides/*.md"):
        fm = parse_frontmatter(path)
        iface = fm.get("interface") or fm.get("contract")
        if not iface or fm.get("status") in ("superseded",):
            continue
        ver = fm.get("version")
        if ver is None:
            continue
        if iface not in latest or version_tuple(ver) > version_tuple(latest[iface][0]):
            latest[iface] = (str(ver), fm.get("status", "?"), path.relative_to(ROOT))
    return latest


def drift_state(pinned: str, latest: str | None) -> tuple[str, str]:
    """-> (emoji, label)."""
    if latest is None:
        return "⚪", "no contract file yet"
    p, l = version_tuple(pinned), version_tuple(latest)
    if l <= p:
        return "🟢", "aligned"
    if l[0] > p[0]:
        return "🔴", f"BREAKING — latest {latest}, review required"
    return "🟠", f"latest {latest} — re-pin when convenient"


def replace_block(path: Path, marker: str, body: str) -> bool:
    text = path.read_text(encoding="utf-8")
    pattern = re.compile(
        rf"(<!-- atlas:{marker}:begin[^>]*-->).*?(<!-- atlas:{marker}:end -->)", re.DOTALL
    )
    if not pattern.search(text):
        print(f"  WARN: no atlas:{marker} markers in {path.relative_to(ROOT)}")
        return False
    path.write_text(pattern.sub(rf"\1\n{body}\n\2", text), encoding="utf-8")
    return True


NAME_EXEMPT = {"README.md", "component.md", "AGENTS.md", "dashboard.md", "INDEX.md"}
NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]*(-v\d+_\d+)?\.md$")
# archives keep historical names; triage is quarantine; reference/ holds provider-homed
# library docs delivered verbatim — the copy is not this vault's to rename (1.21).
NAME_SKIP_DIRS = {"archive", "_triage", "reference"}


def naming_warnings() -> list[str]:
    """Live-folder documents outside the naming canon (AAC-method §4). Warn-only."""
    warns = []
    for pattern in ("components/*/docs/**/*.md", "architecture/**/*.md", "needs/**/*.md"):
        for p in sorted(ROOT.glob(pattern)):
            rel = p.relative_to(ROOT)
            if NAME_SKIP_DIRS & set(rel.parts[:-1]):
                continue
            if p.name in NAME_EXEMPT or NAME_RE.match(p.name):
                continue
            warns.append(rel.as_posix())
    return warns


def ref_stem(ref) -> str:
    """The document stem a `responds_to:` value points at.

    Values are written in several shapes in the field — a vault-relative path, an
    Obsidian [[wikilink]], or prose naming a file. Resolve all of them rather than
    demanding a migration."""
    s = str(ref).strip().strip("[]")
    m = re.search(r"[\w./\\-]+\.md", s)
    token = m.group(0) if m else (s.split()[-1] if s.split() else "")
    return Path(token.replace("\\", "/")).stem


def responds_to_index(slug: str) -> dict:
    """need-document stem -> the provides/ document that answers it.

    The provider already writes the link (`responds_to:`); this makes it load-bearing.
    A component's obligations are then computed, not remembered — the same shape as
    pinned-vs-latest drift (decisions/0004, from an agent-skeleton field finding).
    Archived responses still count: an answer that was later superseded was still given.
    """
    index = {}
    for p in sorted(ROOT.glob(f"components/{slug}/docs/provides/**/*.md")):
        fm = parse_frontmatter(p)
        val = fm.get("responds_to") or fm.get("responds-to")
        if val is None:
            continue
        refs = val if isinstance(val, list) else [val]
        for ref in refs:
            # canonical form is a vault-relative path; free-text mentions still resolve,
            # so existing documents keep working without a migration
            stem = ref_stem(ref)
            if stem:
                index.setdefault(stem, p)
    return index


def responds_to_warnings(graph) -> list[str]:
    """`responds_to:` pointing at a document that does not exist in the vault.

    A response may legitimately answer a need, a proposal, or a living document, so the
    check is existence — not category. Anything narrower cries wolf on correct links."""
    stems = {p.stem for p in ROOT.rglob("*.md")}
    warns, cross_vault = [], 0
    for p in sorted(ROOT.glob("components/*/docs/provides/**/*.md")):
        fm = parse_frontmatter(p)
        val = fm.get("responds_to") or fm.get("responds-to")
        if val is None:
            continue
        for ref in (val if isinstance(val, list) else [val]):
            stem = ref_stem(ref)
            if not stem or stem in stems:
                continue
            # A provider serving OTHER vaults (deliver-and-sweep, §5) answers needs that
            # live in the consuming vault — its responds_to legitimately points outside
            # this one. A path-shaped reference that does not resolve locally is that
            # case, not a typo; warning on each trained the estate's busiest provider
            # to ignore the section (21 false warnings on the Orchestrator, 2026-09-03).
            if "/" in str(ref):
                cross_vault += 1
            else:
                warns.append(f"{p.relative_to(ROOT).as_posix()} — responds_to "
                             f"'{ref}' names no document in the vault")
    if cross_vault:
        warns.append(f"(info) {cross_vault} responds_to link(s) are path-shaped and not "
                     "in this vault — cross-vault answers, unverified locally by design")
    return warns


def addressee_warnings(graph) -> list[str]:
    """needs/ documents whose addressee matches no component (decisions/0003 §4).

    Routing by addressee turns a typo into silent non-delivery, so an unroutable
    addressee must be visible. Warn-only, like naming."""
    slugs = [c["slug"] for c in graph.get("components", [])] + list(WELL_KNOWN_ADDRESSEES)
    # an external provider is a legitimate addressee: asks travel to it by the normal
    # route, picked up when its arch seat reads this vault (§5, decisions/0006)
    slugs += [str(e.get("provider")) for e in graph.get("external") or [] if e.get("provider")]
    warns = []
    for p in sorted(list(ROOT.glob("components/*/docs/needs/*.md"))
                    + list(ROOT.glob("needs/*.md"))):
        fm = parse_frontmatter(p)
        named = addressee(fm)
        if named is None or is_retired(fm):
            continue
        if not any(names_slug(named, s) for s in slugs):
            warns.append(f"{p.relative_to(ROOT).as_posix()} — addressee "
                         f"'{named}' matches no component; it will reach nobody")
        elif not any(names_slug_exactly(named, s) for s in slugs):
            warns.append(f"{p.relative_to(ROOT).as_posix()} — addressee '{named}' "
                         "resolved by prose, not a slug; write the slug (or a list of "
                         "slugs) so delivery cannot turn on wording")
        # nav (the human) mixed with a component slug: the bridge is human<->AI only, so
        # this is a seat trying to reach another seat through the human. Pick one channel.
        comp = [c["slug"] for c in graph.get("components", [])]
        toks = addressee_tokens(named)
        if BRIDGE_ADDRESSEE in toks and any(s in toks for s in comp):
            warns.append(f"{p.relative_to(ROOT).as_posix()} — addressee '{named}' names "
                         "both `nav` (the human) and a component; the bridge is not a "
                         "seat-to-seat relay — address the component's slug alone, or "
                         "`nav` alone for a human decision")
    return warns


def edge_rows(graph, latest):
    rows = []
    for e in graph.get("edges", []):
        lv = latest.get(e["interface"], (None,))[0]
        emoji, label = drift_state(str(e["pinned"]), lv)
        rows.append({**e, "latest": lv or "—", "emoji": emoji, "label": label})
    return rows


def method_drift(graph) -> tuple[str, str]:
    """-> (emoji, message): the vault's method pin vs the method version this validator
    ships with. The method pin is an edge like any other — it gets the same drift
    treatment (minor = informational, major = breaking). Run from a method checkout at
    the pinned tag, the two match and the row reads aligned; run from a newer checkout
    (CI checks out the method default branch = latest release), drift surfaces here."""
    # Read as raw text, never through YAML: an unquoted 1.10 parses as the float 1.1
    # and silently collides with release 1.1 (found on the 1.10 release itself).
    vm = re.search(r'^version:\s*"?([0-9][0-9.]*)"?',
                   (METHOD_ROOT / "AAC-method.md").read_text(encoding="utf-8"), re.MULTILINE)
    mine = vm.group(1) if vm else None
    pin = (graph.get("method") or {}).get("pinned")
    if mine is None:
        return "⚪", "cannot read the method version beside this validator — skipped"
    if pin is None:
        return "🔴", (f"no method: pin in io-graph.yml — pin the latest release "
                      f"(this validator is method {mine})")
    if isinstance(pin, float):
        return "🔴", (f"method pin {pin} is an unquoted YAML number — ambiguous "
                      f"(1.10 reads as 1.1). Quote it: pinned: '{mine}'")
    # The exact tree in use, so a moved or mis-resolved tag is visible on the dashboard
    # instead of hiding behind a matching version NUMBER (decisions: tags are immutable
    # from 1.20; this is the detection half of that rule).
    tag = (run_git(["-C", str(METHOD_ROOT), "describe", "--tags", "--exact-match"]) or
           run_git(["-C", str(METHOD_ROOT), "describe", "--tags", "--always"]) or "?").strip()
    sha = (run_git(["-C", str(METHOD_ROOT), "rev-parse", "--short", "HEAD"]) or "?").strip()
    at = f"{tag} @ {sha}"
    p, m = version_tuple(pin)[:2], version_tuple(str(mine))[:2]
    if p == m:
        return "🟢", f"pinned {pin} — aligned with the running method ({at})"
    if p > m:
        return "🟠", (f"pinned {pin} but running method {mine} — method checkout is "
                      "older than the pin; re-run atlas-sync")
    if m[0] > p[0]:
        return "🔴", f"BREAKING — pinned {pin}, running method {mine}; review required"
    return "🟠", (f"pinned {pin}, running method {mine} ({at}) — newer release available; "
                  "adopt at periodic review, never in a sweep")


def run_git(args: list, timeout: int = 10, cwd: str | None = None) -> str | None:
    try:
        r = subprocess.run(["git", *args], capture_output=True, text=True, timeout=timeout,
                           cwd=cwd, env={**os.environ, "GIT_TERMINAL_PROMPT": "0"})
        return r.stdout if r.returncode == 0 else None
    except (OSError, subprocess.TimeoutExpired):
        return None


def run_git_remote(args: list, timeout: int = 30) -> str | None:
    """Git against a REMOTE, run from outside any repository.

    Never inherit the surrounding checkout's config. actions/checkout writes a
    repo-local http.extraheader carrying the workflow's vault-scoped GITHUB_TOKEN;
    inside that checkout it overrides the global insteadOf credential (the
    ATLAS_ESTATE_TOKEN), so every probe of another private repo 403s and reports
    "unreachable" while the repo is perfectly reachable. Diagnosed and reproduced by
    the agent-skeleton seat, 2026-08-24.
    """
    with tempfile.TemporaryDirectory() as neutral:
        return run_git(args, timeout=timeout, cwd=neutral)


def remote_repo_info(url: str, *branches: str) -> dict | None:
    """Default branch, branch heads, and latest v-tag of a remote — via one ls-remote."""
    pats = ["HEAD"] + [f"refs/heads/{b}" for b in branches if b] + ["refs/tags/*"]
    out = run_git_remote(["ls-remote", "--symref", url, *pats])
    if out is None:
        return None
    info = {"default": None, "heads": {}, "tag": None}
    tags = []
    for line in out.splitlines():
        if line.startswith("ref:"):  # "ref: refs/heads/dev\tHEAD"
            info["default"] = line.split()[1].rsplit("/", 1)[-1]
            continue
        sha, _, ref = line.partition("\t")
        ref = ref.strip()
        if ref.startswith("refs/heads/"):
            info["heads"][ref[len("refs/heads/"):]] = sha
        elif ref.startswith("refs/tags/"):
            tags.append(ref[len("refs/tags/"):].removesuffix("^{}"))
    vt = [t for t in tags if re.fullmatch(r"v\d+(\.\d+)*", t)]
    if vt:
        info["tag"] = max(vt, key=lambda t: version_tuple(t[1:]))
    return info


def component_source(graph, c) -> str:
    """The component's clone URL. Canonical home: its io-graph entry (§5, 1.6+);
    component.md frontmatter is the fallback for pre-1.6 vaults."""
    fm = parse_frontmatter(ROOT / "components" / c["slug"] / "component.md")
    return str(c.get("source") or fm.get("source") or "")


def check_wiring(graph) -> dict:
    """slug -> (emoji, label): is the component's code repo actually wired into the
    protocol? (decisions/0001; opt-in via --check-wiring.) A repo is WIRED iff its
    default branch root has .atlas.conf with SLUG == the component's slug, and a
    committed AGENTS.md — what a fresh clone anywhere gets, not what a local
    checkout claims. Content fetch is a blobless shallow clone + two blob reads.
    Warn-only, always: a component may be unwired while being brought up; it may
    not be unwired invisibly."""
    results = {}
    for c in graph["components"]:
        slug = c["slug"]
        url = component_source(graph, c)
        if not ("://" in url or url.startswith("git@")):
            results[slug] = ("⚪", "unaddressable — `source:` is not a clone URL")
            continue
        with tempfile.TemporaryDirectory() as td:
            if run_git_remote(["clone", "--depth", "1", "--filter=blob:none",
                               "--no-checkout", "--quiet", url, td]) is None:
                results[slug] = ("⚪", "unreachable at check time")
                continue
            conf = run_git(["-C", td, "show", "HEAD:.atlas.conf"])
            agents = run_git(["-C", td, "show", "HEAD:AGENTS.md"])
        if conf is None and agents is None:
            results[slug] = ("🔴", "unwired — no `.atlas.conf`/`AGENTS.md` on the default branch")
            continue
        m = re.search(r'^SLUG="?([^"\r\n]*)"?', conf or "", re.MULTILINE)
        repo_slug = m.group(1) if m else None
        if conf is None:
            results[slug] = ("🔴", "unwired — `AGENTS.md` present but no `.atlas.conf`")
        elif repo_slug != slug:
            results[slug] = ("🔴", f"unwired — `.atlas.conf` SLUG `{repo_slug or '?'}` ≠ `{slug}`")
        elif agents is None:
            results[slug] = ("🔴", "unwired — `.atlas.conf` present but no committed `AGENTS.md`")
        else:
            results[slug] = ("🟢", "wired")
    return results


def external_latest(vault_url: str, provider: str, interface: str):
    """-> (latest_version, note). The newest live contract for `interface` in the
    provider's own vault — a blobless clone plus the provides/ blobs (decisions/0006).
    The clone lands on the provider vault's default branch = its work branch (§9)."""
    with tempfile.TemporaryDirectory() as td:
        if run_git_remote(["clone", "--depth", "1", "--filter=blob:none",
                           "--no-checkout", "--quiet", vault_url, td]) is None:
            return None, "vault unreachable"
        listing = run_git(["-C", td, "ls-tree", "--name-only", "HEAD",
                           f"components/{provider}/docs/provides/"])
        if not listing:
            return None, f"no components/{provider}/docs/provides/ in that vault"
        best = None
        for name in listing.splitlines():
            if not name.endswith(".md"):
                continue
            blob = run_git(["-C", td, "show", f"HEAD:{name}"])
            if blob is None:
                continue
            fm = parse_frontmatter_text(blob)
            if (fm.get("interface") or fm.get("contract")) != interface:
                continue
            if fm.get("status") in ("superseded",):
                continue
            ver = fm.get("version")
            if ver is not None and (best is None or version_tuple(ver) > version_tuple(best)):
                best = str(ver)
        return (best, "") if best else (None, f"no live contract `{interface}` in provider's provides/")


def gen_external_section(graph, check: bool) -> tuple[str, list[str], int]:
    """-> (dashboard md, console lines, worst): the vault's external: pins (§5, 1.16).
    Latest is fetched only when `check` (CI runs --check-wiring; local stays offline)."""
    ext = graph.get("external") or []
    if not ext:
        return "", [], 0
    md = ["**External dependencies** (contracts homed in other vaults):", "",
          "| Interface | Provider | Vault | Pinned | Latest | State |",
          "|---|---|---|---|---|---|"]
    console, worst = [], 0
    for e in ext:
        iface, prov = e.get("interface", "?"), e.get("provider", "?")
        vault = str(e.get("vault", ""))
        vshort = vault.rstrip("/").split("/")[-1].removesuffix(".git") or "?"
        if e.get("pinned") is None:
            # A provider you can address but do not yet build against. Asking for a
            # capability must not require pinning a contract version you cannot see —
            # that is how a guessed literal gets into a vault (§9, and the ARCPlatform
            # seat's field report, 2026-08-28).
            md.append(f"| {'`'+iface+'`' if iface != '?' else '—'} | {prov} | {vshort} "
                      f"| — | — | 🔵 declared provider, nothing pinned |")
            continue
        pin = str(e.get("pinned"))
        if not check:
            md.append(f"| `{iface}` | {prov} | {vshort} | {pin} | – | unchecked (CI checks) |")
            continue
        latest, note = external_latest(vault, prov, iface)
        if latest is None:
            md.append(f"| `{iface}` | {prov} | {vshort} | {pin} | — | ⚪ {note} |")
            console.append(f"  ⚪ external  {iface} from {prov}@{vshort}: {note}")
            continue
        emoji, label = drift_state(pin, latest)
        md.append(f"| `{iface}` | {prov} | {vshort} | {pin} | {latest} | {emoji} {label} |")
        if emoji != "🟢":
            console.append(f"  {emoji} external  {iface} from {prov}@{vshort}  pinned {pin}  ({label})")
        if emoji == "🔴":
            worst = 1
    return "\n".join(md), console, worst


def gen_branch_section(graph, wiring: dict | None = None) -> tuple[str, list[str]]:
    """-> (dashboard markdown, console lines): the per-repo estate table — branch
    status (AAC-method §9) plus, when --check-wiring ran, the Wired column
    (decisions/0001). Network state at regen time; unreachable repos degrade to a
    note, never an error."""
    pol = graph.get("branching") or {}
    work, release = pol.get("work"), pol.get("release")
    console = []

    def wired_cell(name):
        if wiring is None:
            return "–"
        if name not in wiring:
            return "—"
        emoji, label = wiring[name]
        if emoji != "🟢":
            console.append(f"  {emoji} wiring  {name}: {label}")
        return f"{emoji} {label}"

    if not work:
        line = ("no `branching:` policy in io-graph.yml — declare `work:`/`release:` "
                "(AAC-method §9; default template: work `dev`, release `main`)")
        md = [f"**Branch policy:** ⚪ {line}"]
        console.append(f"  ⚪ branching  {line}")
        if wiring is not None:
            md += ["", "| Repo | Wired |", "|---|---|"]
            md += [f"| {s} | {wired_cell(s)} |" for s in wiring]
        return "\n".join(md), console
    head = (f"**Branch policy:** work `{work}`"
            + (f" → release `{release}` (merged by the architecture session at periodic review)"
               if release else ""))
    # Communication planes (§6, comms.md): the hub is opt-in; nav and atlas are always on.
    comms = graph.get("comms") or {}
    hub = ("on" + (f" ({comms.get('channel')})" if comms.get("channel") else "")
           if comms.get("hub") else "off — nav + vault only")
    head += f"\n\n**Comms:** bridge (nav) + vault (atlas) always; hub {hub}."
    md = [head, "", "| Repo | Default branch | Work vs release | Latest tag | Wired |",
          "|---|---|---|---|---|"]
    console.append(f"  🧭 branching  work {work}" + (f" -> release {release}" if release else ""))
    repos = [("vault", (run_git(["-C", str(ROOT), "remote", "get-url", "origin"]) or "").strip())]
    repos += [(c["slug"], component_source(graph, c)) for c in graph["components"]]
    for name, url in repos:
        if not ("://" in url or url.startswith("git@")):
            md.append(f"| {name} | — | _no source URL_ | — | {wired_cell(name)} |")
            continue
        info = remote_repo_info(url, work, release)
        if info is None:
            md.append(f"| {name} | — | _unreachable at regen_ | — | {wired_cell(name)} |")
            continue
        d = info["default"] or "?"
        d_cell = f"`{d}` 🟢" if d == work else f"`{d}` 🔴 policy: `{work}`"
        w, r = info["heads"].get(work), info["heads"].get(release) if release else None
        if w is None:
            wr = f"🔴 no `{work}` branch"
        elif release is None or r is None:
            wr = "—" if release is None else f"no `{release}` branch"
        else:
            wr = "in sync" if w == r else "unreleased changes on work"
        md.append(f"| {name} | {d_cell} | {wr} | {info['tag'] or '—'} | {wired_cell(name)} |")
        if d != work or w is None:
            console.append(f"  🔴 branch  {name}: default '{d}', policy '{work}'"
                           + ("" if w else f" (no {work} branch)"))
    return "\n".join(md), console


def gen_graph_md(graph, rows) -> str:
    names = {c["slug"]: c for c in graph["components"]}
    ids = {slug: re.sub(r"[^a-z0-9]", "", slug) for slug in names}
    lines = [
        "---", "title: I/O Graph — rendered view", "type: graph-view", "---", "",
        "# I/O Graph (rendered)", "",
        f"> **Generated file** — {GENERATED_NOTE}.",
        "> Arrows point **provider → consumer** (upstream → downstream).", "",
        "```mermaid", "flowchart LR",
        "    classDef sink fill:#2d3a2e,stroke:#7fbf7f,color:#eee;",
    ]
    for slug, c in names.items():
        m = c.get("maturity", "?")
        cls = ":::sink" if c.get("sink") else ""  # `sink: true` on the io-graph entry
        lines.append(f'    {ids[slug]}["{c["name"]}<br/><small>{m}</small>"]{cls}')
    for r in rows:
        arrow = "==>" if r.get("mode") == "collaboration" else "-->"
        mark = "" if r["emoji"] == "🟢" else f" {r['emoji']}"
        lines.append(f'    {ids[r["from"]]} {arrow}|"{r["interface"]}{mark}"| {ids[r["to"]]}')
    lines += [
        "```", "",
        "**Legend:** solid = x-as-a-service · thick `==` = collaboration · "
        "🟠 minor drift · 🔴 breaking drift · ⚪ contract not yet published in Atlas.", "",
        "## Edges", "",
        "| Provider → Consumer | Interface | Mode | Pinned | Latest | State |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {names[r['from']]['name']} → {names[r['to']]['name']} | {r['interface']} "
            f"| {r.get('mode', '?')} | {r['pinned']} | {r['latest']} | {r['emoji']} {r['label']} |"
        )
    return "\n".join(lines) + "\n"


def gen_component_block(slug, graph, rows, names) -> str:
    up = [r for r in rows if r["to"] == slug]
    down = [r for r in rows if r["from"] == slug]
    def fmt(r, other):
        link = f"[[{other}/component|{names[other]['name']}]]"
        return f"{link} — `{r['interface']}` (pinned {r['pinned']}) {r['emoji']}"
    lines = []
    lines.append("- **Upstream (I depend on):** " + ("; ".join(fmt(r, r["from"]) for r in up) or "_none_"))
    lines.append("- **Downstream (depend on me):** " + ("; ".join(fmt(r, r["to"]) for r in down) or "_none — terminal sink_"))
    lines.append("- **I provide** (`docs/provides/`): " + (", ".join(f"`{r['interface']}`" for r in down) or "_no registered interfaces_"))
    lines.append("- **I read:** providers' `docs/provides/` above; my consumers' `docs/needs/` for feedback.")
    return "\n".join(lines)


def delivered_external(graph) -> list:
    """External contracts the provider has DELIVERED into this vault.

    A provider homed in another vault answers in its own `provides/` and delivers a
    marked copy to `components/<provider>/docs/provides/` here — the one sanctioned
    write into another project's vault, and already fenced by the CI guard, which lets
    branch `atlas/<provider>/*` touch exactly that folder. So the content is local:
    the briefing reads it in place, with no cross-vault credential (the consumer's
    seats have none). External dependencies are declared per VAULT, not per component,
    so a delivered contract is an input to every component here.
    """
    out = []
    for e in graph.get("external") or []:
        prov = e.get("provider")
        if not prov:
            continue
        folder = ROOT / "components" / str(prov) / "docs" / "provides"
        if not folder.is_dir():
            continue
        iface, pin = e.get("interface"), e.get("pinned")
        if iface and pin is not None:
            path, ver, note = contract_at_pin(folder, str(iface), str(pin))
            if path is not None:
                out.append({"provider": prov, "interface": str(iface), "pinned": str(pin),
                            "path": path.relative_to(ROOT).as_posix(), "version": ver,
                            "note": note})
            continue
        # declared provider, nothing pinned: take whatever it has delivered
        for path in sorted(folder.glob("*.md")):
            fm = parse_frontmatter(path)
            if str(fm.get("status", "")).lower().startswith("superseded"):
                continue
            out.append({"provider": prov,
                        "interface": str(fm.get("interface") or path.stem),
                        "pinned": None, "path": path.relative_to(ROOT).as_posix(),
                        "version": str(fm.get("version", "?")), "note": ""})
    return out


def gen_manifest(slug, rows) -> dict:
    return {
        "component": slug,
        "generated_by": "Atlas/tools/atlas_validate.py",
        "read_before_working": {
            "constitution": "architecture/constitution.md",
            "inputs": [
                {
                    "provider": r["from"],
                    "interface": r["interface"],
                    "pinned": r["pinned"],
                    "path": f"components/{r['from']}/docs/provides/",
                    "state": r["label"],
                }
                for r in rows if r["to"] == slug
            ],
            "consumer_feedback": [
                {"consumer": r["to"], "path": f"components/{r['to']}/docs/needs/"}
                for r in rows if r["from"] == slug
            ],
            "proposals": "architecture/proposals/",
            "external_inputs": DELIVERED_EXTERNAL,
        },
    }


# --------------------------------------------------------------------------- #
# Context mode — the retrieval boundary (AAC-method §6).                       #
# Everything below only READS the vault and concatenates; it never mutates.    #
# --------------------------------------------------------------------------- #

def read_doc(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8").strip()
    except OSError as exc:
        return f"_[unreadable: {exc}]_"


def contract_artifacts(contract: Path, fm: dict) -> tuple[list, list]:
    """-> (artifacts, errors). A contract may declare machine-readable sidecars that
    live beside it — OpenAPI, JSON Schema — under `artifacts:` (names, or {file, sha256}).
    Byte-faithful: nothing here reads the content as anything but bytes. A declared
    sha256 is VERIFIED; missing files or a mismatch are errors, never warnings — a
    consumer generating models from these must not be invited to guess (1.21, from a
    blocks-android need)."""
    import hashlib
    decl = fm.get("artifacts") or []
    arts, errs = [], []
    for d in decl if isinstance(decl, list) else [decl]:
        name = d.get("file") if isinstance(d, dict) else str(d)
        want = (d.get("sha256") if isinstance(d, dict) else None)
        if not name or "/" in str(name) or str(name).startswith("."):
            errs.append(f"{contract.relative_to(ROOT).as_posix()}: artifact name "
                        f"{name!r} must be a plain filename beside the contract")
            continue
        src = contract.parent / name
        if not src.is_file():
            errs.append(f"{contract.relative_to(ROOT).as_posix()}: declared artifact "
                        f"`{name}` is missing beside it")
            continue
        data = src.read_bytes()
        digest = hashlib.sha256(data).hexdigest()
        if want and str(want).lower() != digest:
            errs.append(f"{contract.relative_to(ROOT).as_posix()}: artifact `{name}` "
                        f"sha256 {digest[:12]}… does not match declared {str(want)[:12]}… "
                        "— bytes changed under a published version; bump the contract")
            continue
        arts.append({"file": name, "path": src.relative_to(ROOT).as_posix(),
                     "bytes": len(data), "sha256": digest, "declared": bool(want)})
    return arts, errs


def deliver_artifacts(arts: list, contract: Path, interface: str, version: str,
                      dest_root: Path | None) -> list:
    """Copy exact bytes to <dest_root>/<interface>/<file> and return rendered rows.
    Delivered as FILES beside the briefing, not inline: the invariant forbids browsing
    the vault, not receiving exact artefacts — and a large schema belongs in a code
    generator's hands, not in the model's context window."""
    import shutil
    rows = []
    for a in arts:
        where = ""
        if dest_root is not None:
            d = dest_root / interface
            d.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(ROOT / a["path"], d / a["file"])   # bytes, never reserialized
            where = (d / a["file"]).as_posix()
        rows.append(f"| `{a['file']}` | {version} | {a['bytes']:,} | `{a['sha256'][:16]}…` "
                    f"| `{a['path']}` | {'`'+where+'`' if where else '_not written (no --artifacts-dir)_'} |")
    return rows


ARTIFACT_TABLE_HEAD = ("| Artifact | Version | Bytes | sha256 | Provider path | Delivered to |\n"
                       "|---|---|---|---|---|---|")


def contract_at_pin(provides_dir: Path, interface: str, pinned: str):
    """-> (path, version, note) — the contract file for `interface` at `pinned`.

    Resolution rule (explicit): on an exact MAJOR.MINOR match, the live folder wins
    over archive/. If the pin is gone entirely, fall back to the newest **live**
    version with a note (drift the session must see); archive/ is consulted for the
    fallback only when the live folder has no candidate at all.
    """
    def scan(folder: Path):
        out = []
        for p in sorted(folder.glob("*.md")):
            fm = parse_frontmatter(p)
            if (fm.get("interface") or fm.get("contract")) != interface:
                continue
            ver = fm.get("version")
            if ver is not None:
                out.append((p, str(ver)))
        return out

    live, archived = scan(provides_dir), scan(provides_dir / "archive")
    if not live and not archived:
        return None, None, f"no contract file for `{interface}` under {provides_dir}"
    want = version_tuple(pinned)[:2]
    for p, ver in live + archived:  # live listed first — live wins on exact match
        if version_tuple(ver)[:2] == want:
            return p, ver, ""
    p, ver = max(live or archived, key=lambda c: version_tuple(c[1]))
    return p, ver, f"pinned {pinned} not found — showing latest {ver}; re-pin deliberately"


# `to:` is canonical (AAC-method §3); `addressed-to:` is accepted because a
# substantial minority of documents in the field use it, and an unrecognised key
# used to fall through to "addressed to everyone" — fail-open in the selector
# (Atlas decisions/0003, from AgentEco ADR-0008).
ADDRESSEE_KEYS = ("to", "addressed-to", "addressed_to")
BRIDGE_ADDRESSEE = "nav"     # the human, via the Nav vault bridge (AAC-method §9)
METHOD_ADDRESSEE = "atlas"   # the method seat — every vault pins the method, so every
                             # vault may need to ask its owner (it is not an external:
                             # provider; the method is pinned by `method:`)
WELL_KNOWN_ADDRESSEES = (BRIDGE_ADDRESSEE, METHOD_ADDRESSEE)


def addressee(fm: dict) -> str | None:
    """The addressee field of a needs/ doc, whichever spelling it uses; None if absent."""
    for key in ADDRESSEE_KEYS:
        val = fm.get(key)
        if val is None:
            continue
        if isinstance(val, list):
            return "; ".join(str(v) for v in val)
        return str(val)
    return None


def addressee_head(value: str) -> str:
    """The addressing part of the field, with trailing commentary removed.

    A parenthetical is commentary, not an address: `to: atlas (AAC-method owner;
    agent-skeleton's seat docs affected too)` is addressed to atlas. Matching the whole
    string found `agent-skeleton` inside the aside and delivered there instead —
    silently, and to a plausible wrong recipient (field defect, 2026-08-29)."""
    return re.split(r"[(\[]", str(value), 1)[0]


def addressee_tokens(value: str) -> list:
    """The head split into candidate slugs."""
    return [tok.strip().lower()
            for tok in re.split(r"[;,/]|\band\b", addressee_head(value))
            if tok.strip()]


def names_slug(value: str, slug: str) -> bool:
    """Does an addressee field name this slug? Exact token first; substring within the
    head as the compatibility fallback for prose ("RBAC-compile workstream")."""
    slug = slug.lower()
    return slug in addressee_tokens(value) or slug in addressee_head(value).lower()


def names_slug_exactly(value: str, slug: str) -> bool:
    return slug.lower() in addressee_tokens(value)


RETIRED_STATUSES = ("superseded", "resolved", "closed", "done")


def is_retired(fm: dict) -> bool:
    """A need the raiser has closed. The raiser owns `status:` and already writes these
    words; the emitter just ignored all but `superseded`, so a resolved ask kept landing
    in its addressee's briefing every session, in full, forever (1.21)."""
    s = str(fm.get("status", "")).lower()
    return any(s.startswith(w) for w in RETIRED_STATUSES)


def addressed_to(fm: dict, slug: str) -> bool:
    """A needs/ doc is in scope if it names the slug, or names nobody at all."""
    value = addressee(fm)
    return True if value is None else names_slug(value, slug)


ALL_TOKENS = ("all", "all components", "everyone", "*")


def affects_slug(fm: dict, slug: str) -> bool:
    """Does a document's scope (`affects:` / `target_component:` / `related:`) name this
    slug? Routed with the same token-aware matching `to:` gets (§3) — the old bare
    substring test meant `affects: [all components]` matched NOBODY, so a project-wide
    proposal reached no briefing precisely while in flight (arc-platform finding,
    2026-09-03). The well-known tokens 'all' / 'all components' reach every slug."""
    vals = []
    for k in ("affects", "target_component", "related"):
        v = fm.get(k)
        if v is None:
            continue
        vals += [str(x) for x in v] if isinstance(v, list) else [str(v)]
    for v in vals:
        head = addressee_head(v).strip().lower()
        if head in ALL_TOKENS or names_slug(v, slug):
            return True
    return False


def proposal_in_flight(fm: dict, slug: str) -> bool:
    status = str(fm.get("status", "proposed")).lower()
    if any(s in status for s in ("accepted", "rejected", "implemented", "superseded",
                                 "withdrawn", "done", "closed")):
        return False
    return affects_slug(fm, slug)


def architecture_in_force() -> list:
    """The 'architecture in force' index: accepted decisions and standalone
    architecture documents, as a LIST the session reads on demand. The briefing is a
    reading list (§6) — an entry here makes reading that document retrieval, not
    browsing. Bodies are deliberately not embedded: a decision binds every component,
    and N slugs on one seat would carry it N times (arc-platform findings, 2026-09-03).
    An index also honours 'summarised context is never the design record' exactly —
    the session reads the record itself, not a summary of it."""
    lines = []
    dec = sorted((ROOT / "architecture" / "decisions").glob("*.md"))         if (ROOT / "architecture" / "decisions").is_dir() else []
    for p in dec:
        fm = parse_frontmatter(p)
        aff = fm.get("affects", "")
        aff = ", ".join(str(a) for a in aff) if isinstance(aff, list) else str(aff)
        lines.append(f"- `{p.relative_to(ROOT).as_posix()}` — "
                     f"{fm.get('title', p.stem)} (status: {fm.get('status', '?')}"
                     + (f"; affects: {aff}" if aff else "") + ")")
    for p in sorted((ROOT / "architecture").glob("*.md")):
        if p.name == "constitution.md":
            continue
        fm = parse_frontmatter(p)
        lines.append(f"- `{p.relative_to(ROOT).as_posix()}` — "
                     f"{fm.get('title', p.stem)} (status: {fm.get('status', 'active')})")
    return lines


def reference_library() -> list:
    """The reference/ index: provider-homed library docs delivered on demand to this
    vault (method 1.21, orchestrator ADR-0007). Listed, not embedded — shared know-how a
    session reads when a task points at it; reading a listed file is retrieval, not
    browsing. Delivered verbatim and read-only; the one home is the provider's
    docs/library/, named in each copy's banner."""
    ref = ROOT / "reference"
    if not ref.is_dir():
        return []
    lines = []
    for p in sorted(ref.rglob("*.md")):
        if p.name == "INDEX.md":
            continue
        fm = parse_frontmatter(p)
        lines.append(f"- `{p.relative_to(ROOT).as_posix()}` — "
                     f"{fm.get('title', p.stem)}"
                     + (f" (from {fm.get('interface', '?')})" if fm.get('library') else ""))
    return lines


def emit_context(slug_arg: str, out: str | None, artifacts_dir: str | None = None) -> int:
    """Emit the briefing for one slug, or ONE seat briefing for several
    (comma-separated). A seat holding N components pays for its briefing once per
    SESSION, not once per slug: shared sections — constitution, architecture index,
    delivered external contracts, needs addressed to several held slugs, proposals —
    appear exactly once, then each slug gets its own inputs, solo needs and drift.
    On a real four-repo seat the per-slug shape injected 84KB of which 71% was the
    same text repeated (arc-platform finding, 2026-09-03)."""
    slugs = [s.strip() for s in str(slug_arg).split(",") if s.strip()]
    seat = len(slugs) > 1
    dest = Path(artifacts_dir).resolve() if artifacts_dir else None
    art_bytes, art_count, art_errors = 0, 0, []
    delivered_ifaces: set = set()

    readings = {}
    for s in slugs:
        mp = ROOT / "registry" / ".compiled" / s / "io-manifest.yml"
        if not mp.exists():
            print(f"No {mp.relative_to(ROOT).as_posix()} in the vault — the compiled "
                  "manifests must be committed (AAC-method §5); regenerate with the "
                  "validator (no flags) on the vault's default branch.", file=sys.stderr)
            return 2
        readings[s] = yaml.safe_load(mp.read_text(encoding="utf-8")).get(
            "read_before_working", {})

    who = slugs[0] if not seat else "seat briefing — " + ", ".join(slugs)
    sections: list[str] = [
        f"# ATLAS-CONTEXT — {who}",
        "",
        "> Generated by tools/atlas_validate.py --emit-context from the committed",
        "> io-manifests. Do not edit.",
        "> This is the session's complete reading list. Consult the wider vault only if",
        "> this file is insufficient — and treat that as a defect in `registry/io-graph.yml`:",
        "> fix the graph, don't browse.",
    ]
    if seat:
        sections.append("> One briefing for every component this seat holds: shared "
                        "sections appear once; per-component sections follow (1.21).")

    # ---- shared: constitution ------------------------------------------------------
    const_rel = readings[slugs[0]].get("constitution", "architecture/constitution.md")
    sections += [f"\n---\n\n## Constitution — `{const_rel}`\n", read_doc(ROOT / const_rel)]

    # ---- shared: architecture in force (index — reading it is retrieval) -----------
    arch_idx = architecture_in_force()
    if arch_idx:
        sections += ["\n---\n\n# Architecture in force — read on demand (this is "
                     "retrieval, not browsing)\n",
                     "The documents below govern this vault. **Reading a document "
                     "listed here is part of the protocol** — a structural change is a "
                     "design act, and the design record is these files, never this "
                     "briefing's prose.\n", *arch_idx]

    ref_idx = reference_library()
    if ref_idx:
        sections += ["\n---\n\n# Reference library — delivered here, read on demand "
                     "(retrieval, not browsing)\n",
                     "Provider-homed reference docs delivered to `reference/`. Shared "
                     "know-how, read when a task needs it — not a contract, not a "
                     "dependency, and never edited here (the one home is the provider's "
                     "`docs/library/`, named in each file's banner).\n", *ref_idx]

    def emit_artifacts(contract_path: Path, iface: str, ver: str, delivered: bool):
        nonlocal art_bytes, art_count
        arts, errs = contract_artifacts(contract_path, parse_frontmatter(contract_path))
        art_errors.extend(errs)
        if arts:
            rows = deliver_artifacts(arts, contract_path, iface, ver, dest)
            art_count += len(arts)
            art_bytes += sum(a["bytes"] for a in arts)
            label = ("delivered with the contract" if delivered
                     else "generate from these, never from the prose")
            sections.extend([f"\n**Raw artifacts** (exact bytes; {label}):\n",
                             ARTIFACT_TABLE_HEAD, *rows])

    # ---- shared: contracts delivered from other vaults (vault-scoped by definition) -
    ext_inputs = readings[slugs[0]].get("external_inputs") or []
    if ext_inputs:
        sections.append("\n---\n\n# Inputs — contracts delivered from other vaults"
                        + (" (vault-scoped: shown once for the whole seat)" if seat else "")
                        + "\n")
        for x in ext_inputs:
            head = (f"## `{x['interface']}` from {x['provider']}"
                    + (f" — pinned {x['pinned']}" if x.get("pinned") else " — not pinned"))
            if x.get("note"):
                head += f"\n\n> ⚠ {x['note']}"
            sections += [f"{head}\n\n**Source:** `{x['path']}` (version "
                         f"{x.get('version', '?')}; authored in the provider's own vault "
                         "and delivered here — never edit this copy)\n",
                         read_doc(ROOT / x["path"])]
            emit_artifacts(ROOT / x["path"], str(x["interface"]),
                           str(x.get("version", "?")), delivered=True)

    # ---- needs: ONE scan, each doc classified by which held slugs it reaches -------
    edge_dirs = {s: {(ROOT / fb["path"]).resolve()
                     for fb in readings[s].get("consumer_feedback", [])} for s in slugs}
    answers = {s: responds_to_index(s) for s in slugs}
    needs_dirs = sorted(ROOT.glob("components/*/docs/needs"))
    if (ROOT / "needs").is_dir():
        needs_dirs.append(ROOT / "needs")
    shared_needs, solo_needs = [], {s: [] for s in slugs}
    outstanding, done_count = 0, 0
    for needs_dir in needs_dirs:
        rel = needs_dir.relative_to(ROOT)
        owner = rel.parts[1] if rel.parts[0] == "components" else "the vault"
        for p in sorted(needs_dir.glob("*.md")):
            fm = parse_frontmatter(p)
            if is_retired(fm):
                continue
            named = addressee(fm)
            matches = []
            for s in slugs:
                if owner == s:
                    continue                       # its own outbox, not feedback to it
                if named is None:
                    if needs_dir.resolve() in edge_dirs[s]:
                        matches.append(s)
                elif names_slug(named, s):
                    matches.append(s)
            if not matches:
                continue
            why = (f"addressed to `{named}`" if named is not None
                   else f"no addressee — delivered because {owner} is a consumer's provider")
            entry = (p, fm, owner, why, matches)
            (shared_needs if len(matches) > 1 else solo_needs[matches[0]]).append(entry)

    def render_need(entry, for_slugs):
        nonlocal outstanding, done_count
        p, fm, owner, why, matches = entry
        rel_p = p.relative_to(ROOT).as_posix()
        bits = [f"{k}: {fm[k]}" for k in ("need", "status", "version") if fm.get(k)]
        meta = "; ".join(bits) or "no metadata"
        states = {s: answers[s].get(p.stem) for s in for_slugs}
        unanswered = [s for s, a in states.items() if a is None]
        if not unanswered:
            done_count += 1
            by = "; ".join(f"`{a.relative_to(ROOT).as_posix()}`"
                           for a in dict.fromkeys(states.values()))
            sections.append(f"- answered — `{rel_p}` ({meta}) → {by}")
            return
        outstanding += 1
        tag = "**UNANSWERED**" if len(for_slugs) == 1 else \
              f"**UNANSWERED** for {', '.join(unanswered)}" + \
              ("".join(f"; answered by `{states[s].relative_to(ROOT).as_posix()}` ({s})"
                       for s in for_slugs if states[s] is not None))
        aud = f" — to {', '.join(matches)}" if len(matches) > 1 else ""
        sections.extend([f"## {tag} — from {owner}: `{rel_p}`{aud}\n\n"
                         f"_{meta}. Delivered because: {why}._\n", read_doc(p)])

    if seat and shared_needs:
        sections.append("\n---\n\n# Needs addressed to several of my components "
                        "(shown once)\n")
        for e in shared_needs:
            render_need(e, e[4])

    # ---- per-slug sections ---------------------------------------------------------
    drift_rows = []
    for s in slugs:
        reading = readings[s]
        inputs = reading.get("inputs", [])
        if seat:
            sections.append(f"\n---\n\n# Component: {s}\n")
        sections.append("\n---\n\n" + (f"## {s} — inputs" if seat else
                        "# Inputs — upstream contracts I build against") + "\n")
        if not inputs:
            sections.append("_none — no upstream edges._")
        for inp in inputs:
            path, ver, note = contract_at_pin(
                ROOT / inp["path"], inp["interface"], str(inp["pinned"]))
            head = (f"## `{inp['interface']}` from {inp['provider']} — "
                    f"pinned {inp['pinned']}, state: {inp.get('state', '?')}")
            if note:
                head += f"\n\n> ⚠ {note}"
            if path is None:
                sections += [head, "_contract not yet published._"]
            else:
                key = (path, inp["interface"])
                already = key in delivered_ifaces
                delivered_ifaces.add(key)
                sections += [f"{head}\n\n**Source:** `{path.relative_to(ROOT).as_posix()}` "
                             f"(version {ver})\n",
                             ("_full text above (shared input of this seat)._"
                              if already else read_doc(path))]
                if not already:
                    emit_artifacts(path, str(inp["interface"]), str(ver), delivered=False)
            drift_rows += [(s, inp)]
        solo = solo_needs[s]
        sections.append("\n" + (f"## {s} — needs addressed to me" if seat else
                        "\n---\n\n# Consumer feedback — needs addressed to me") + "\n")
        if not solo and not (seat and shared_needs):
            sections.append("_none pending._")
        for e in solo:
            render_need(e, [s])

    if outstanding or done_count:
        sections.append(f"\n_{outstanding} unanswered, {done_count} answered (one line "
                        "each; retired asks — resolved/closed/done/superseded — are not "
                        "shown). An entry is answered when the addressee's "
                        "`docs/provides/` carries `responds_to:` naming it._")

    # ---- shared: proposals (union, once) -------------------------------------------
    proposals_dir = ROOT / readings[slugs[0]].get("proposals", "architecture/proposals/")
    sections.append("\n---\n\n# In-flight proposals affecting "
                    + ("this seat's components" if seat else "me") + "\n")
    hits = []
    for p in sorted(proposals_dir.glob("*.md")):
        fm = parse_frontmatter(p)
        mine = [s for s in slugs if proposal_in_flight(fm, s)]
        if mine:
            hits.append((p, fm, mine))
    if not hits:
        sections.append("_none in flight._")
    for p, fm, mine in hits:
        aff = f" — affects (of mine): {', '.join(mine)}" if seat else ""
        sections += [f"## `{p.relative_to(ROOT).as_posix()}` "
                     f"(status: {fm.get('status', '?')}){aff}\n", read_doc(p)]

    # ---- drift summary --------------------------------------------------------------
    sections.append("\n---\n\n# Drift summary (pinned vs latest, per edge)\n")
    if drift_rows:
        cols = "| Slug | Provider | Interface | Pinned | State |" if seat else \
               "| Provider | Interface | Pinned | State |"
        sections.append(cols)
        sections.append("|---|---|---|---|---|" if seat else "|---|---|---|---|")
        for s, i in drift_rows:
            lead = f"| {s} " if seat else ""
            sections.append(f"{lead}| {i['provider']} | `{i['interface']}` | "
                            f"{i['pinned']} | {i.get('state', '?')} |")
    else:
        sections.append("_no upstream edges._")

    if art_errors:
        for e in art_errors:
            print(f"ATLAS-CONTEXT: ARTIFACT ERROR — {e}", file=sys.stderr)
        return 2
    for src, detail in dict.fromkeys(FRONTMATTER_ERRORS):
        print(f"ATLAS-CONTEXT: WARNING — frontmatter of `{src}` does not parse "
              f"({detail}); it has NO fields for this briefing — a contract there reads "
              "as unpublished, an ask as unaddressed", file=sys.stderr)
    text = "\n".join(sections) + "\n"
    if out:
        Path(out).write_text(text, encoding="utf-8")
        print(f"wrote {out}", file=sys.stderr)
    else:
        sys.stdout.write(text)
    size = len(text.encode("utf-8"))
    label = who if not seat else f"seat ({len(slugs)} components)"
    print(f"ATLAS-CONTEXT for {label}: {size:,} bytes, ~{size // 4:,} tokens"
          + (" — SESSION TOTAL in one artefact" if seat else ""), file=sys.stderr)
    if art_count:
        print(f"ATLAS-CONTEXT raw artifacts: {art_count} file(s), {art_bytes:,} bytes "
              f"-> {dest.as_posix() if dest else 'not written (pass --artifacts-dir)'}",
              file=sys.stderr)
    return 0


def main(wiring_flag: bool = False) -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    if not (ROOT / "registry" / "io-graph.yml").exists():
        print(f"No registry/io-graph.yml under {ROOT} — run from a project-vault root "
              "or pass the vault path as the first argument.")
        return 2
    graph = load_graph()
    names = {c["slug"]: c for c in graph["components"]}

    # -- referential integrity ------------------------------------------------
    errors = []
    for e in graph.get("edges", []):
        for end in ("from", "to"):
            if e[end] not in names:
                errors.append(f"edge {e['from']}->{e['to']}: unknown component '{e[end]}'")
    for c in graph["components"]:
        if not (ROOT / "components" / c["slug"] / "component.md").exists():
            errors.append(f"component '{c['slug']}' has no components/{c['slug']}/component.md")
    for cpath in ROOT.glob("components/*/docs/provides/*.md"):
        _, aerrs = contract_artifacts(cpath, parse_frontmatter(cpath))
        errors += aerrs
    if errors:
        print("INTEGRITY ERRORS:")
        for err in errors:
            print(f"  ✗ {err}")
        return 1

    latest = latest_contract_versions()
    rows = edge_rows(graph, latest)
    global DELIVERED_EXTERNAL
    DELIVERED_EXTERNAL = delivered_external(graph)

    # -- regenerate derived views ---------------------------------------------
    (ROOT / "registry" / "graph.md").write_text(gen_graph_md(graph, rows), encoding="utf-8")
    print("regenerated registry/graph.md")

    m_emoji, m_label = method_drift(graph)
    wiring = check_wiring(graph) if wiring_flag else None
    branch_md, branch_console = gen_branch_section(graph, wiring)
    ext_md, ext_console, ext_worst = gen_external_section(graph, wiring_flag)
    drift_table = "\n".join(
        [f"**Method:** {m_emoji} {m_label}", ""]
        + ([ext_md, ""] if ext_md else [])
        + [branch_md, "",
         "| Edge (provider → consumer) | Interface | Pinned | Latest | State |", "|---|---|---|---|---|"]
        + [
            f"| {r['from']} → {r['to']} | {r['interface']} | {r['pinned']} | {r['latest']} | {r['emoji']} {r['label']} |"
            for r in sorted(rows, key=lambda r: ("🔴🟠⚪🟢".index(r["emoji"]),))
        ]
    )
    replace_block(ROOT / "dashboard.md", "drift", drift_table)
    print("regenerated dashboard.md drift panel")

    for slug in names:
        replace_block(
            ROOT / "components" / slug / "component.md", "edges",
            gen_component_block(slug, graph, rows, names),
        )
        out = ROOT / "registry" / ".compiled" / slug
        out.mkdir(parents=True, exist_ok=True)
        (out / "io-manifest.yml").write_text(
            yaml.safe_dump(gen_manifest(slug, rows), sort_keys=False, allow_unicode=True),
            encoding="utf-8",
        )
    print(f"regenerated {len(names)} component edge blocks + io-manifests")

    # -- drift report -----------------------------------------------------------
    print("\nDRIFT REPORT")
    worst = 0
    print(f"  {m_emoji} method  {m_label}")
    if m_emoji == "🔴":
        worst = 1
    for line in branch_console:
        print(line)
    for line in ext_console:
        print(line)
    worst = max(worst, ext_worst)
    for r in rows:
        print(f"  {r['emoji']} {r['from']} → {r['to']}  {r['interface']}  pinned {r['pinned']}  ({r['label']})")
        if r["emoji"] == "🔴":
            worst = 1
    print(f"\n{sum(r['emoji'] == '🟢' for r in rows)} aligned, "
          f"{sum(r['emoji'] == '🟠' for r in rows)} minor drift, "
          f"{sum(r['emoji'] == '🔴' for r in rows)} breaking, "
          f"{sum(r['emoji'] == '⚪' for r in rows)} unpublished")

    # -- frontmatter that will not parse — NOT warn-only (see parse_frontmatter_text) --
    if FRONTMATTER_ERRORS:
        uniq = list(dict.fromkeys(FRONTMATTER_ERRORS))
        print(f"\nFRONTMATTER — {len(uniq)} document(s) whose frontmatter does not parse; "
              "they have NO fields as far as every check above is concerned (a published "
              "contract reads as never published, a needs doc reaches nobody):")
        for src, detail in uniq:
            print(f"  \U0001F534 {src} — {detail}")
        worst = max(worst, 1)

    # -- naming canon (AAC-method §4) — warn-only, never affects the exit code --
    unroutable = addressee_warnings(graph)
    if unroutable:
        print(f"\nROUTING — {len(unroutable)} needs document(s) with an unroutable "
              "addressee (AAC-method §3; warn-only):")
        for w in unroutable:
            print(f"  ⚠ {w}")

    dangling = responds_to_warnings(graph)
    if dangling:
        print(f"\nRESPONSES — {len(dangling)} responds_to link(s) naming no document "
              "in the vault (warn-only):")
        for w in dangling:
            print(f"  ⚠ {w}")

    warns = naming_warnings()
    if warns:
        print(f"\nNAMING — {len(warns)} live-folder name(s) outside the canon "
              "(lowercase-kebab, version -vX_Y; AAC-method §4; warn-only):")
        for w in warns:
            print(f"  ⚠ {w}")
    return worst


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("root", nargs="?", default=".",
                    help="project-vault root (default: cwd)")
    ap.add_argument("--emit-context", metavar="SLUG[,SLUG...]",
                    help="emit ATLAS-CONTEXT.md instead of validating; comma-separated "
                         "slugs emit ONE seat briefing with shared sections deduplicated")
    ap.add_argument("--check-wiring", action="store_true",
                    help="also check each component repo is wired (fetches .atlas.conf "
                         "and AGENTS.md from its source: remote; warn-only; decisions/0001)")
    ap.add_argument("--artifacts-dir", metavar="DIR",
                    help="with --emit-context: copy declared contract artifacts (exact "
                         "bytes) to DIR/<interface>/<file>, beside the briefing")
    ap.add_argument("--out", metavar="PATH",
                    help="with --emit-context: write to PATH instead of stdout")
    args = ap.parse_args()
    ROOT = Path(args.root).resolve()
    if hasattr(sys.stderr, "reconfigure"):
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    if args.emit_context:
        if hasattr(sys.stdout, "reconfigure"):
            sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.exit(emit_context(args.emit_context, args.out, args.artifacts_dir))
    sys.exit(main(args.check_wiring))
